name: Share Elo Score

on:
  push:
    branches:
      - main

jobs:
  share-elo-score:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy elo score file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "jrank/registry/registry.jsonl"
          destination_repo: "yuzu-ai/public-website"
          destination_folder: "src/content/pages"
          user_email: "yudataguy@gmail.com"
          user_name: "yudataguy"
          commit_message: "send elo file to public website repo"
  
  share-chart:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'jrank/charts'
          destination-github-username: 'yuzu-ai'
          destination-repository-name: 'public-website'
          user-email: "contact@yuzuai.jp"
          target-branch: main
          target-directory: "public/images/charts"
          commit-message: "trasnfer charts to yuzuai website repo"