name: Share Elo Score

on:
    push:
        branches:
            - main

jobs:
    # copy_elo_score:
    #     name: Copy elo score to website repo
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v2
    #         - name: List elo score
    #           run: ls elo/registry
    #         - name: Push to website repo
    #           uses: cpina/github-action-push-to-another-repository@main
    #           env:
    #             API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    #           with:
    #             source-directory: "elo/registry/output"
    #             target-directory: "src/content/pages/elo"
    #             destination-github-username: "yuzu-ai"
    #             destination-repository-name: "public-website"
    #             create-target-branch-if-needed: true
    #             user-email: "yudataguy@gmail.com"

    
    copy-elo-benchmark-file:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Copy elo benchmark file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'elo/registry/output/benchmark.md'
          destination_repo: 'yuzu-ai/public-website'
          destination_folder: 'src/content/pages'
          user_email: 'yudataguy@gmail.com'
          user_name: 'yudataguy'
          commit_message: 'Update elo score'